# Generated by Django 5.2 on 2025-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('correction', models.BooleanField(default=False)),
                ('quiztry', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'progression par page',
            },
        ),
        migrations.CreateModel(
            name='PropositionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'enregistrement des propositions',
            },
        ),
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'progression par question',
            },
        ),
        migrations.CreateModel(
            name='TutoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'progression par tuto',
            },
        ),
    ]
