# Generated by Django 5.2 on 2025-09-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('tuto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageprogress',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.page'),
        ),
    ]
