# Generated by Django 4.2 on 2025-04-07 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuto', '0005_alter_proposition_proposition_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoprogress',
            name='tuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoprogress', to='tuto.tutorial'),
        ),
        migrations.AlterField(
            model_name='tutoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoprogress', to=settings.AUTH_USER_MODEL),
        ),
    ]
