# Generated by Django 5.2 on 2025-09-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0002_initial'),
        ('tuto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propositionprogress',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.proposition'),
        ),
        migrations.AddField(
            model_name='propositionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.question'),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutoprogress',
            name='tuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoprogress', to='tuto.tutorial'),
        ),
        migrations.AddField(
            model_name='tutoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoprogress', to=settings.AUTH_USER_MODEL),
        ),
    ]
