# Generated by Django 5.2 on 2026-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
