# Generated by Django 4.2.16 on 2025-02-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_restriction_user_restriction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restriction',
            options={'verbose_name': "Restriction d'accè"},
        ),
    ]
