# Generated by Django 4.2.16 on 2025-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_restriction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='restriction',
            field=models.ManyToManyField(blank=True, related_name='user', to='user.restriction'),
        ),
    ]
