# Generated by Django 5.2 on 2025-09-12 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenttype', models.CharField(choices=[('TI', 'Titre'), ('ST', 'Sous-titre'), ('PA', 'Paragraphe'), ('IM', 'Image'), ('VI', 'Video'), ('LI', 'Liste')], max_length=20)),
                ('texte', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tuto/images/')),
                ('video', models.FileField(blank=True, upload_to='tuto/videos/')),
                ('percent_scale', models.IntegerField(default=100)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Page')),
                ('page_title', models.CharField(max_length=200, verbose_name='Titre')),
            ],
            options={
                'verbose_name': 'page',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='TutoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TutoBase', max_length=200)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de mise à jour')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tuto/images/')),
                ('resume', models.TextField(max_length=2000)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de mise à jour')),
                ('in_progress', models.BooleanField(default=True)),
                ('submitted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'tutoriel',
                'ordering': ['created_at'],
                'permissions': (('publie_tuto', 'rendre un tutoriel public'),),
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True)),
                ('position', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.content')),
            ],
            options={
                'verbose_name': 'listitem',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.page'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('multiresponse', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('explication', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.page')),
            ],
            options={
                'verbose_name': 'question',
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('proposition', models.TextField()),
                ('good_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.question')),
            ],
            options={
                'verbose_name': 'proposition',
            },
        ),
    ]
