# Generated by Django 4.2.16 on 2025-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_restriction_user_restriction'),
        ('tuto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='restriction',
            field=models.ManyToManyField(related_name='tutorial', to='user.restriction'),
        ),
    ]
