# Generated by Django 5.2 on 2025-09-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuto', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.ManyToManyField(related_name='tutorial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='tuto.category'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='restriction',
            field=models.ManyToManyField(blank=True, related_name='tutorial', to='user.restriction'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutobase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='tuto.tutobase'),
        ),
        migrations.AddField(
            model_name='page',
            name='tuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuto.tutorial'),
        ),
    ]
