# Generated by Django 4.2.16 on 2025-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_restriction_options'),
        ('tuto', '0002_tutorial_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='restriction',
            field=models.ManyToManyField(blank=True, related_name='tutorial', to='user.restriction'),
        ),
    ]
