# Generated by Django 4.2.16 on 2025-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuto', '0003_alter_tutorial_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, upload_to='tuto/videos/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contenttype',
            field=models.CharField(choices=[('TI', 'Titre'), ('ST', 'Sous-titre'), ('PA', 'Paragraphe'), ('IM', 'Image'), ('VI', 'Video'), ('LI', 'Liste')], max_length=20),
        ),
    ]
