# Generated by Django 4.2.16 on 2025-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuto', '0004_content_video_alter_content_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='proposition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='explication',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
