# Generated by Django 4.2.16 on 2025-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuto', '0005_alter_proposition_proposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='percent_scale',
            field=models.IntegerField(default=100),
        ),
    ]
