# Generated by Django 4.2.16 on 2025-01-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcontent',
            name='explication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='libelles',
            name='explication',
            field=models.TextField(blank=True),
        ),
    ]
