# Generated by Django 4.2.16 on 2025-01-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_defaultcontent_explication_libelles_explication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcontent',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='home/files/'),
        ),
        migrations.AlterField(
            model_name='defaultcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/'),
        ),
        migrations.AlterField(
            model_name='libelles',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='home/files/'),
        ),
        migrations.AlterField(
            model_name='libelles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/'),
        ),
    ]
