name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/Mooc
            git pull origin main
            docker compose -f docker-compose.yml build
            docker compose -f docker-compose.yml up -d
            docker compose -f docker-compose.yml exec -T web python mooc/manage.py migrate --noinput
            docker compose -f docker-compose.yml exec -T web python mooc/manage.py collectstatic --noinput
            sudo chmod o+x /var/lib/docker/volumes/mooc_static_files/
            sudo chmod o+x /var/lib/docker/volumes/mooc_media_files/
